### ISSUE TITLE
Missing standard communication event definition

### ISSUE THREAD

**Issue by softwindren** [w3c/miniapp-lifecycle#22]
Considering the existing implementations of MiniApp widely use the architecture that separates logic from rendering (the white paper describes this as well). Usually, the MiniApp framework and native framework are preconfigured in a Super-App to process API invoking of MiniApp. However, the definition of communication events between MiniApp and MiniApp framework is not found in the lifecycle document. If there is no unified interface, how can the standard MiniApp of vendor foo run in the App of vendor bar? Considering the value of standards and interconnection requirements, I think this part should be standardized.

![image](https://user-images.githubusercontent.com/27724172/156087268-6b3b0467-e81b-4711-8fe6-c0c9f6019a4b.png)

**Comment by QingAn** [comment]
> Considering the value of standards and interconnection requirements, I think this part should be standardized.

Will discuss it within MiniApp WG

**Comment by QingAn** [comment]
We had a brief discussion in MiniApp WG 2022-03-24 meeting.
We are wondering that Who will use this interface? Developers or MiniApp Platform vendors?
It is a topic that needs further discussion. @softwindren Could you attend our next WG meeting?

**Comment by Sharonzd** [comment]
@zitao

**Comment by espinr** [comment]
The scope of this issue is related to the implementation of the JS bridge in the user agents. It's about how to define an abstract API for communication between the user agent and the native features in the OS. 

It could be interesting to explore, but I think it's not related to the lifecycle specification. So I think you can close this issue. I also invite @softwindren to think more about the idea and submit a more solid proposal in the future. Happy to follow up!
